// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db_model.proto

package modelpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Collection struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TenantID             string   `protobuf:"bytes,2,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	CollectionName       string   `protobuf:"bytes,3,opt,name=collectionName,proto3" json:"collectionName,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AutoID               bool     `protobuf:"varint,5,opt,name=autoID,proto3" json:"autoID,omitempty"`
	Ts                   uint64   `protobuf:"varint,6,opt,name=ts,proto3" json:"ts,omitempty"`
	Properties           string   `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	CreatedTime          uint64   `protobuf:"varint,8,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime          uint64   `protobuf:"varint,9,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fa3123635ae304f, []int{0}
}

func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (m *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(m, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Collection) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

func (m *Collection) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *Collection) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Collection) GetAutoID() bool {
	if m != nil {
		return m.AutoID
	}
	return false
}

func (m *Collection) GetTs() uint64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *Collection) GetProperties() string {
	if m != nil {
		return m.Properties
	}
	return ""
}

func (m *Collection) GetCreatedTime() uint64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Collection) GetUpdatedTime() uint64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Collection)(nil), "milvus.proto.model.Collection")
}

func init() { proto.RegisterFile("db_model.proto", fileDescriptor_4fa3123635ae304f) }

var fileDescriptor_4fa3123635ae304f = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbd, 0x4a, 0xc4, 0x40,
	0x14, 0x85, 0x49, 0x76, 0x8d, 0xd9, 0xbb, 0x92, 0x62, 0x0a, 0x19, 0x2c, 0x24, 0x5a, 0x48, 0x1a,
	0x13, 0x50, 0x9f, 0x40, 0xd3, 0xa4, 0xb1, 0x08, 0x56, 0x36, 0x4b, 0x7e, 0x2e, 0x3a, 0x30, 0x7f,
	0xcc, 0xdc, 0xf8, 0x1c, 0x3e, 0xb2, 0x64, 0x12, 0xd6, 0x65, 0xbb, 0x39, 0xdf, 0x7c, 0x67, 0x18,
	0x0e, 0x64, 0x63, 0x7f, 0x50, 0x66, 0x44, 0x59, 0x5a, 0x67, 0xc8, 0x30, 0xa6, 0x84, 0xfc, 0x99,
	0xfc, 0x92, 0xca, 0x70, 0x73, 0xff, 0x1b, 0x03, 0xbc, 0x19, 0x29, 0x71, 0x20, 0x61, 0x34, 0xcb,
	0x20, 0x6e, 0x6a, 0x1e, 0xe5, 0x51, 0xb1, 0x69, 0xe3, 0xa6, 0x66, 0x37, 0x90, 0x12, 0xea, 0x4e,
	0x53, 0x53, 0xf3, 0x38, 0x8f, 0x8a, 0x5d, 0x7b, 0xcc, 0xec, 0x01, 0xb2, 0xe1, 0xd8, 0x7c, 0xef,
	0x14, 0xf2, 0x4d, 0x30, 0xce, 0x28, 0xcb, 0x61, 0x3f, 0xa2, 0x1f, 0x9c, 0xb0, 0x33, 0xe2, 0xdb,
	0x20, 0x9d, 0x22, 0x76, 0x0d, 0x49, 0x37, 0x91, 0x69, 0x6a, 0x7e, 0x91, 0x47, 0x45, 0xda, 0xae,
	0x69, 0xfe, 0x0d, 0x79, 0x9e, 0xe4, 0x51, 0xb1, 0x6d, 0x63, 0xf2, 0xec, 0x16, 0xc0, 0x3a, 0x63,
	0xd1, 0x91, 0x40, 0xcf, 0x2f, 0xc3, 0x43, 0x27, 0x84, 0xdd, 0xc1, 0xd5, 0xe0, 0xb0, 0x23, 0x1c,
	0x0f, 0x24, 0x14, 0xf2, 0x34, 0x34, 0xf7, 0x2b, 0xfb, 0x10, 0x0a, 0x67, 0x65, 0xb2, 0xe3, 0xbf,
	0xb2, 0x5b, 0x94, 0x95, 0xcd, 0xca, 0xeb, 0xcb, 0xe7, 0xd3, 0x97, 0xa0, 0xef, 0xa9, 0x2f, 0x07,
	0xa3, 0xaa, 0x65, 0xb3, 0x47, 0x61, 0xd6, 0x53, 0x25, 0x34, 0xa1, 0xd3, 0x9d, 0xac, 0xc2, 0x8c,
	0x55, 0x98, 0xd1, 0xf6, 0x7d, 0x12, 0xe2, 0xf3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x35,
	0x78, 0xed, 0x75, 0x01, 0x00, 0x00,
}
